<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Icons\Address.png" />
    <None Remove="Icons\Address1.png" />
    <None Remove="Icons\city.png" />
    <None Remove="Icons\Contact.png" />
    <None Remove="Icons\Customer_Id.png" />
    <None Remove="Icons\Customer_ID2.png" />
    <None Remove="Icons\Delete.png" />
    <None Remove="Icons\Distance.png" />
    <None Remove="Icons\Distance1.png" />
    <None Remove="Icons\exit.png" />
    <None Remove="Icons\phone.png" />
    <None Remove="Icons\Pincode.png" />
    <None Remove="Icons\save.png" />
    <None Remove="Icons\Site.png" />
    <None Remove="login_bg.PNG" />
    <None Remove="Login_bg_new.PNG" />
    <None Remove="project_small_i.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="MQTTnet" Version="5.1.0.1559" />
    <PackageReference Include="Sharp7" Version="1.1.84" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icons\Address.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Address1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\city.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Contact.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Customer_ID2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Delete.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Distance.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Distance1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\exit.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\phone.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Pincode.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\save.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Site.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="login_bg.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Login_bg_new.PNG">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="project_small_i.png" />
  </ItemGroup>

</Project>
